name: Build Verification

on:
  push:
    branches:
      - main
      - git-format-workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install dependencies
        working-directory: expert-matcher-ui
        run: yarn install

    
        
      - name: Format code
        working-directory: expert-matcher-ui
        run: |
             echo "Running formatter..."
             yarn format
      
      
      - name: Build project
        working-directory: expert-matcher-ui
        run: yarn build

